#!/usr/bin/env bash
# scripts/00_install_codex_cli_undo.sh — defensively undo the per-user Codex
# CLI configuration written by 00_install_codex_cli.sh.
#
# WHAT IT UNDOES
# --------------
#   (d) Removes the three managed profile files ONLY IF each exists with the
#       exact byte content written by the installer.
#   (c) Removes the exact marker-delimited root profile-selection block from
#       ~/.codex/config.toml ONLY IF present and byte-identical. If the root
#       profile was user-owned (same value but no installer block), this script
#       leaves it alone.
#   (b) Removes the exact ~/.bashrc PATH snippet written by the installer, if
#       present. If ~/.local/bin was already on PATH before install, there is
#       nothing to remove.
#   (a) Does NOT uninstall the Codex binary/package and never touches auth,
#       sessions, logs, history, plugins, MCP config, themes, or other Codex
#       state under ~/.codex.
#
# DESIGN — TWO-PHASE, ALL-OR-NOTHING
# ----------------------------------
# Phase 1 verifies every exact byte sequence and collects every problem before
# any write. If there is a problem, the script exits non-zero and touches
# nothing. Phase 2 performs all removals with tempfile + atomic rename where a
# rewrite is needed.
#
# Usage:
#   bash scripts/00_install_codex_cli_undo.sh

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
. "$SCRIPT_DIR/lib/common.sh"

require_non_root
require_ubuntu_noble
require_command python3

TARGET_USER="$(id -un)"
TARGET_HOME="$HOME"
[ "$TARGET_HOME" = "/home/$TARGET_USER" ] \
    || die "expected HOME=/home/$TARGET_USER, got '$TARGET_HOME' — refusing to write into a non-standard home"

if [ -n "${CODEX_HOME:-}" ] && [ "$CODEX_HOME" != "$TARGET_HOME/.codex" ]; then
    die "CODEX_HOME is set to '$CODEX_HOME'. This undo script manages the default $TARGET_HOME/.codex only; unset CODEX_HOME and re-run."
fi

BASHRC="$TARGET_HOME/.bashrc"
CODEX_HOME_DIR="$TARGET_HOME/.codex"
CONFIG="$CODEX_HOME_DIR/config.toml"
SAFE_PROFILE="$CODEX_HOME_DIR/personal-server-safe.config.toml"
WORKSPACE_PROFILE="$CODEX_HOME_DIR/personal-server-workspace.config.toml"
DANGER_PROFILE="$CODEX_HOME_DIR/personal-server-container-danger.config.toml"

[ -f "$BASHRC" ] || die "$BASHRC does not exist — nothing to undo for PATH step"

section "verify Codex managed state before undo"

export U_BASHRC="$BASHRC"
export U_CONFIG="$CONFIG"
export U_SAFE_PROFILE="$SAFE_PROFILE"
export U_WORKSPACE_PROFILE="$WORKSPACE_PROFILE"
export U_DANGER_PROFILE="$DANGER_PROFILE"

python3 - <<'PYEOF'
from __future__ import annotations

import os
import pathlib
import sys
import tempfile
import tomllib

BASHRC = pathlib.Path(os.environ["U_BASHRC"])
CONFIG = pathlib.Path(os.environ["U_CONFIG"])
SAFE_PROFILE = pathlib.Path(os.environ["U_SAFE_PROFILE"])
WORKSPACE_PROFILE = pathlib.Path(os.environ["U_WORKSPACE_PROFILE"])
DANGER_PROFILE = pathlib.Path(os.environ["U_DANGER_PROFILE"])

PROFILE_NAME = "personal-server-safe"
ROOT_BEGIN = "# >>> codex config profile (managed by 00_install_codex_cli.sh) >>>"
ROOT_END = "# <<< codex config profile (managed by 00_install_codex_cli.sh) <<<"
ROOT_BLOCK = f"""{ROOT_BEGIN}
# Select the conservative host-safe profile by default. Do not edit this block
# by hand; delete the whole block and re-run the installer if you want it
# recreated. Project, thread, runtime, and CLI overrides can still supersede
# this selection, so verify effective state with /status inside Codex.
profile = \"{PROFILE_NAME}\"
{ROOT_END}
"""

COMMON_HEADER = """# Managed by scripts/00_install_codex_cli.sh.
# Do not edit this file by hand. Re-run the installer to recreate it, or run
# scripts/00_install_codex_cli_undo.sh to remove only exact managed state.
#
# Source-audited rationale:
# - Pin model/reasoning to avoid alias/catalog/default drift.
# - Avoid trusted-project workspace-write as the default host posture.
# - Harden spawned shell environment so secrets are not inherited by default.
# - Disable prompt history persistence, analytics, feedback, and startup update
#   checks on this personal infrastructure workstation.

"""
SAFE_CONTENT = COMMON_HEADER + """model = \"gpt-5.5\"
model_provider = \"openai\"
model_reasoning_effort = \"xhigh\"
plan_mode_reasoning_effort = \"xhigh\"
model_reasoning_summary = \"auto\"
model_verbosity = \"high\"

approval_policy = \"on-request\"
sandbox_mode = \"read-only\"
web_search = \"disabled\"
file_opener = \"none\"
check_for_update_on_startup = false
hide_agent_reasoning = false
show_raw_agent_reasoning = false

[shell_environment_policy]
inherit = \"core\"
ignore_default_excludes = false
exclude = [
  \"*KEY*\",
  \"*SECRET*\",
  \"*TOKEN*\",
  \"AWS_*\",
  \"AZURE_*\",
  \"GITHUB_TOKEN\",
  \"OPENAI_API_KEY\",
  \"ANTHROPIC_API_KEY\",
]
set = {}
include_only = []
experimental_use_profile = false

[history]
persistence = \"none\"

[analytics]
enabled = false

[feedback]
enabled = false
"""
WORKSPACE_CONTENT = COMMON_HEADER + """model = \"gpt-5.5\"
model_provider = \"openai\"
model_reasoning_effort = \"xhigh\"
plan_mode_reasoning_effort = \"xhigh\"
model_reasoning_summary = \"auto\"
model_verbosity = \"high\"

approval_policy = \"on-request\"
sandbox_mode = \"workspace-write\"
web_search = \"disabled\"
file_opener = \"none\"
check_for_update_on_startup = false

[sandbox_workspace_write]
writable_roots = []
network_access = false
exclude_tmpdir_env_var = true
exclude_slash_tmp = true

[shell_environment_policy]
inherit = \"core\"
ignore_default_excludes = false
exclude = [
  \"*KEY*\",
  \"*SECRET*\",
  \"*TOKEN*\",
  \"AWS_*\",
  \"AZURE_*\",
  \"GITHUB_TOKEN\",
  \"OPENAI_API_KEY\",
  \"ANTHROPIC_API_KEY\",
]
set = {}
include_only = []
experimental_use_profile = false

[history]
persistence = \"none\"

[analytics]
enabled = false

[feedback]
enabled = false
"""
DANGER_CONTENT = COMMON_HEADER + """# CONTAINER/VM ONLY. This disables Codex's approvals and sandbox. Use only in a
# disposable Docker/VM/container that provides the real containment boundary.
model = \"gpt-5.5\"
model_provider = \"openai\"
model_reasoning_effort = \"xhigh\"
plan_mode_reasoning_effort = \"xhigh\"
model_reasoning_summary = \"auto\"
model_verbosity = \"high\"

approval_policy = \"never\"
sandbox_mode = \"danger-full-access\"
web_search = \"live\"
file_opener = \"none\"
check_for_update_on_startup = false

[shell_environment_policy]
inherit = \"core\"
ignore_default_excludes = false
exclude = [
  \"*KEY*\",
  \"*SECRET*\",
  \"*TOKEN*\",
  \"AWS_*\",
  \"AZURE_*\",
  \"GITHUB_TOKEN\",
  \"OPENAI_API_KEY\",
  \"ANTHROPIC_API_KEY\",
]
set = {}
include_only = []
experimental_use_profile = false

[history]
persistence = \"none\"

[analytics]
enabled = false

[feedback]
enabled = false
"""

STEP_B_APPEND = (
    "\n"
    "# Added by 00_install_codex_cli.sh — codex lives in ~/.local/bin\n"
    "export PATH=\"$HOME/.local/bin:$PATH\"\n"
)

problems: list[str] = []


def read(path: pathlib.Path) -> str:
    return path.read_text(encoding="utf-8")


def atomic_write(path: pathlib.Path, text: str) -> None:
    fd, tmp = tempfile.mkstemp(prefix=path.name + ".new.", dir=str(path.parent))
    try:
        with os.fdopen(fd, "w", encoding="utf-8") as f:
            f.write(text)
        os.replace(tmp, path)
    except BaseException:
        try:
            os.unlink(tmp)
        except FileNotFoundError:
            pass
        raise

# Phase 1: verify config block if present. Missing config/block is okay: install
# may have left a user-owned matching profile selection alone.
config_text = ""
if CONFIG.exists():
    if not CONFIG.is_file():
        problems.append(f"{CONFIG}: exists but is not a regular file")
    else:
        config_text = read(CONFIG)
        try:
            tomllib.loads(config_text or "")
        except tomllib.TOMLDecodeError as e:
            problems.append(f"{CONFIG}: not valid TOML: {e}")
        n_begin = config_text.count(ROOT_BEGIN)
        n_end = config_text.count(ROOT_END)
        if n_begin != n_end:
            problems.append(f"{CONFIG}: managed profile-selection markers are unbalanced ({n_begin} begin, {n_end} end)")
        elif n_begin > 1:
            problems.append(f"{CONFIG}: more than one managed profile-selection block exists")
        elif n_begin == 1 and ROOT_BLOCK not in config_text:
            problems.append(f"{CONFIG}: managed profile-selection block is present but differs from installer expectation")

for path, expected in [
    (SAFE_PROFILE, SAFE_CONTENT),
    (WORKSPACE_PROFILE, WORKSPACE_CONTENT),
    (DANGER_PROFILE, DANGER_CONTENT),
]:
    if not path.exists():
        problems.append(f"{path}: managed profile is missing")
    elif not path.is_file():
        problems.append(f"{path}: exists but is not a regular file")
    elif read(path) != expected:
        problems.append(f"{path}: content differs from installer-managed bytes")

bashrc_text = read(BASHRC)
n_b = bashrc_text.count(STEP_B_APPEND)
if n_b > 1:
    problems.append(f"{BASHRC}: Codex PATH snippet appears {n_b} times; expected 0 or 1")

if problems:
    print("[fatal] Phase 1 verification failed — refusing to undo anything.", file=sys.stderr)
    print("        No file has been touched. Problems:", file=sys.stderr)
    for p in problems:
        print(f"  - {p}", file=sys.stderr)
    sys.exit(2)

print("[info] Phase 1: managed Codex state verified.")

# Phase 2: remove exact state.
for path in [SAFE_PROFILE, WORKSPACE_PROFILE, DANGER_PROFILE]:
    path.unlink()
    print(f"[info] deleted {path}")

if CONFIG.exists() and ROOT_BLOCK in config_text:
    new_config = config_text.replace(ROOT_BLOCK + "\n", "", 1)
    if new_config == config_text:
        new_config = config_text.replace(ROOT_BLOCK, "", 1)
    tomllib.loads(new_config or "")
    atomic_write(CONFIG, new_config)
    print(f"[info] removed managed profile-selection block from {CONFIG}")
else:
    print(f"[info] no installer-owned profile-selection block in {CONFIG}; leaving config.toml alone")

if n_b == 1:
    new_bashrc = bashrc_text.replace(STEP_B_APPEND, "", 1)
    atomic_write(BASHRC, new_bashrc)
    print(f"[info] removed Codex PATH snippet from {BASHRC}")
else:
    print(f"[info] no installer-owned Codex PATH snippet in {BASHRC}; leaving PATH config alone")

print("[info] Codex managed configuration undo complete")
PYEOF

section "success — Codex CLI configuration reverted"
info "Codex binary/package, auth, sessions, logs, history, plugins, MCP config,"
info "and all unmanaged ~/.codex state were intentionally preserved."
